import { FileDown, Download } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { EmissionBreakdown } from '../lib/carbonCalculator';
import { RecommendationItem } from '../lib/recommendations';
import { MLPrediction } from '../lib/mlEngine';

interface ReportGeneratorProps {
  userName: string;
  emissions: EmissionBreakdown;
  recommendations: RecommendationItem[];
  prediction?: MLPrediction;
}

export default function ReportGenerator({ userName, emissions, recommendations, prediction }: ReportGeneratorProps) {
  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFillColor(16, 185, 129);
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('EcoTrace', 15, 20);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Carbon Footprint Report', 15, 30);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Personal Information', 15, 55);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${userName || 'Anonymous User'}`, 15, 65);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 15, 72);

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Emission Summary', 15, 90);

    autoTable(doc, {
      startY: 95,
      head: [['Category', 'Emissions (kg CO₂e/year)', 'Percentage']],
      body: [
        ['Transport', emissions.transport.toFixed(2), `${((emissions.transport / emissions.total) * 100).toFixed(1)}%`],
        ['Energy', emissions.energy.toFixed(2), `${((emissions.energy / emissions.total) * 100).toFixed(1)}%`],
        ['Diet', emissions.diet.toFixed(2), `${((emissions.diet / emissions.total) * 100).toFixed(1)}%`],
        ['Waste', emissions.waste.toFixed(2), `${((emissions.waste / emissions.total) * 100).toFixed(1)}%`],
        ['TOTAL', emissions.total.toFixed(2), '100%'],
      ],
      theme: 'striped',
      headStyles: { fillColor: [16, 185, 129] },
      styles: { fontSize: 10 },
      columnStyles: {
        0: { cellWidth: 60 },
        1: { cellWidth: 70, halign: 'right' },
        2: { cellWidth: 50, halign: 'right' },
      },
    });

    const finalY = (doc as any).lastAutoTable.finalY;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`Classification: ${emissions.category} Emitter`, 15, finalY + 15);

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Top Recommendations', 15, finalY + 30);

    autoTable(doc, {
      startY: finalY + 35,
      head: [['Priority', 'Recommendation', 'Potential Reduction']],
      body: recommendations.slice(0, 5).map((rec, idx) => [
        `${idx + 1}`,
        rec.text,
        `${rec.potentialReduction.toFixed(0)} kg CO₂e`,
      ]),
      theme: 'grid',
      headStyles: { fillColor: [16, 185, 129] },
      styles: { fontSize: 9, cellPadding: 5 },
      columnStyles: {
        0: { cellWidth: 15, halign: 'center' },
        1: { cellWidth: 130 },
        2: { cellWidth: 45, halign: 'right' },
      },
    });

    const recFinalY = (doc as any).lastAutoTable.finalY;

    if (prediction && recFinalY < 250) {
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Future Predictions', 15, recFinalY + 15);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`1 Year Prediction: ${prediction.predictedEmissions1Year.toFixed(2)} kg CO₂e`, 15, recFinalY + 25);
      doc.text(`2 Year Prediction: ${prediction.predictedEmissions2Year.toFixed(2)} kg CO₂e`, 15, recFinalY + 32);
      doc.text(`Trend: ${prediction.trendDirection.charAt(0).toUpperCase() + prediction.trendDirection.slice(1)}`, 15, recFinalY + 39);
      doc.text(`Model Confidence: ${(prediction.confidenceScore * 100).toFixed(0)}%`, 15, recFinalY + 46);
    }

    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by EcoTrace - Know your impact, shape your future', pageWidth / 2, 285, { align: 'center' });

    doc.save(`EcoTrace_Report_${userName || 'Anonymous'}_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const generateCSV = () => {
    const csvContent = [
      ['EcoTrace Carbon Footprint Report'],
      [''],
      ['Personal Information'],
      ['Name', userName || 'Anonymous User'],
      ['Date', new Date().toLocaleDateString()],
      [''],
      ['Emission Summary'],
      ['Category', 'Emissions (kg CO₂e/year)', 'Percentage'],
      ['Transport', emissions.transport.toFixed(2), `${((emissions.transport / emissions.total) * 100).toFixed(1)}%`],
      ['Energy', emissions.energy.toFixed(2), `${((emissions.energy / emissions.total) * 100).toFixed(1)}%`],
      ['Diet', emissions.diet.toFixed(2), `${((emissions.diet / emissions.total) * 100).toFixed(1)}%`],
      ['Waste', emissions.waste.toFixed(2), `${((emissions.waste / emissions.total) * 100).toFixed(1)}%`],
      ['TOTAL', emissions.total.toFixed(2), '100%'],
      [''],
      ['Classification', emissions.category],
      [''],
      ['Recommendations'],
      ['Priority', 'Recommendation', 'Potential Reduction (kg CO₂e)'],
      ...recommendations.map((rec, idx) => [
        `${idx + 1}`,
        rec.text,
        rec.potentialReduction.toFixed(0),
      ]),
    ];

    if (prediction) {
      csvContent.push(
        [''],
        ['Future Predictions'],
        ['1 Year Prediction (kg CO₂e)', prediction.predictedEmissions1Year.toFixed(2)],
        ['2 Year Prediction (kg CO₂e)', prediction.predictedEmissions2Year.toFixed(2)],
        ['Trend', prediction.trendDirection],
        ['Model Confidence', `${(prediction.confidenceScore * 100).toFixed(0)}%`],
      );
    }

    const csv = csvContent.map(row => row.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `EcoTrace_Report_${userName || 'Anonymous'}_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white rounded-xl p-6 shadow-lg">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center">
          <FileDown className="w-6 h-6 text-blue-600" />
        </div>
        <div>
          <h3 className="text-xl font-semibold text-gray-800">Download Your Report</h3>
          <p className="text-sm text-gray-600">Save your carbon footprint analysis</p>
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-4">
        <button
          onClick={generatePDF}
          className="flex items-center justify-center gap-3 bg-gradient-to-r from-red-600 to-red-700 text-white py-4 px-6 rounded-xl font-semibold shadow-md hover:from-red-700 hover:to-red-800 transform hover:scale-[1.02] transition-all"
        >
          <Download className="w-5 h-5" />
          Download PDF Report
        </button>

        <button
          onClick={generateCSV}
          className="flex items-center justify-center gap-3 bg-gradient-to-r from-green-600 to-teal-600 text-white py-4 px-6 rounded-xl font-semibold shadow-md hover:from-green-700 hover:to-teal-700 transform hover:scale-[1.02] transition-all"
        >
          <Download className="w-5 h-5" />
          Download CSV Data
        </button>
      </div>
    </div>
  );
}
